#!/bin/bash

function show_help() {
	echo "usage: $0 <monitor_interface> <out_interface>"
	exit 1
}

trap ctrl_c INT
function ctrl_c() {
    echo "[*] Killing Processes..."
    killall dnsmasq &> /dev/null
    killall hostapd &> /dev/null
}

if [ "$EUID" -ne 0 ]; then
	echo "[*] Please run as root"
	exit 1
fi

if [ $# -eq 0 ]; then
	show_help
fi

I_MON=$1
I_OUT=$2

ifconfig $I_MON 10.0.0.1/24 up
dnsmasq -C dnsmasq.conf
sysctl -w net.ipv4.ip_forward=1 &> /dev/null

iptables -P FORWARD ACCEPT
iptables --table nat -A POSTROUTING -o $I_OUT -j MASQUERADE

hostapd hostapd.conf
